version: '3.8'

networks:
  ltf_networks:
    driver: bridge

services:
  ltf_microservices:
    container_name: discovery_server
    environment:
      - TZ=UTC
    build: 
      context: ../Discovery_Server
    ports:
      - "8080:8080"
    volumes:
      - ../Discovery_Server:/app
    networks:
      - ltf_networks

  redis:
    container_name: redis_kiwi
    environment:
      - TZ=UTC
    build:
      context: ./redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/app
    networks:
      - kiwi_networks

  mysql:
    container_name: kiwidb
    
    build: 
      context: ./mysql
    ports:
      - "3306:3306"
    networks:
      - kiwi_networks
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - TZ=UTC
    

# docker compose -p kiwi_backend up -d